/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GuideText from "./script/GuideText"
import guideBtn from "./script/guideBtn"
import GuideRule from "./script/GuideRule"
import Game from "./script/Game"
import GameStart from "./script/GameStart"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="1.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GuideText.ts",GuideText);
        reg("script/guideBtn.ts",guideBtn);
        reg("script/GuideRule.ts",GuideRule);
        reg("script/Game.ts",Game);
        reg("script/GameStart.ts",GameStart);
    }
}
GameConfig.init();